version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: local.dockerfile
    container_name: s3-api-node
    ports:
      - "3001:3001"
    env_file:
      - .env.development
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    command:  yarn run start
